window.DCG_ADVENTURES = window.DCG_ADVENTURES || {};
window.DCG_ADVENTURES['the-rock'] = {
  id: 'the-rock', title: 'The Rock', creator: 'Anthony Ferlazzo',
  canonicalUrl: 'https://aferlazzo.github.io/The-rock/',
  seriesHome: 'https://aferlazzo.github.io/driver-confidence-guide/',
  shareText: 'THE ROCK — You were just going to buy groceries. What would you do?',
  resumeText: 'You were in the middle of one very ordinary trip to the grocery store.',
  startNode: 'start',
  nodes: {
    start: { hideBrand: true, text: `<p>You’re driving to the store for groceries.</p><p>A Toyota 4x4 is ahead of you.</p><p>Then it happens—</p><p class="impact">a rock in the road.</p><p>The truck rolls over it.</p><p>You see it too late to ignore it.</p><p>It’s bigger than you thought.</p><p>And now it’s directly in your path.</p><p><strong>Right front tire. No time.</strong></p><p class="impact">What do you do?</p>`, choices: [{ label:'Drive over it', detail:'Hope it clears the underside of your car.', next:'driveOver' },{ label:'Swerve around it', detail:'Try to avoid it before impact.', next:'swerve' }] },
    driveOver: { text: `<p><strong>THUMP.</strong></p><p>The right front tire clears the rock.</p><p>Then you hear a hard metallic <strong>CLANG</strong> underneath the car.</p><p>You keep moving, but now there’s a faint scraping sound.</p><div class="explain">Driving over an object can be safer than a sudden swerve in some situations, especially when traffic or loss of control makes steering away risky. But clearance matters: an object that passes under a taller vehicle may strike a lower one.</div><p class="impact">What do you do next?</p>`, choices:[{ label:'Keep driving to the store', detail:'The car still moves and no warning light is on.', next:'continueAfterImpact' },{ label:'Slow down and pull over safely', detail:'Find out what that sound means before continuing.', next:'safeStop' }] },
    swerve: { text:`<p>You snap the wheel left.</p><p>The rock flashes past your right tire.</p><p><strong>HOOOOONK!</strong></p><p>A sedan is beside you in the next lane.</p><p>You correct back into your lane, heart pounding.</p><div class="explain">Avoiding the rock worked—but the maneuver created a different hazard. Emergency steering decisions depend on what is around you, not just what is in front of you. Space beside the car is part of the decision.</div><p class="impact">Now what?</p>`, choices:[{ label:'Keep driving normally', detail:'The rock is behind you. Crisis over.', next:'afterSwerveContinue' },{ label:'Ease off and create space', detail:'Settle the car, check mirrors, and regain a safety cushion.', next:'regainSpace' }] },
    continueAfterImpact: { text:`<p>You continue toward the store.</p><p>The scraping gets louder.</p><p>Then a red warning symbol appears on the dashboard.</p><p>You don’t recognize it.</p><div class="explain">The situation has changed. A new sound plus a warning indicator means you have more evidence than you had a moment ago. Good decisions should update when new information appears.</div><p class="impact">Your move?</p>`, choices:[{ label:'Keep going until you understand the light', detail:'You’re only a few minutes from the store.', next:'badContinue' },{ label:'Pull over safely now', detail:'Stop adding risk while you figure out what changed.', next:'safeStop' }] },
    safeStop: { text:`<p>You signal, slow down, and pull into a safe parking area away from traffic.</p><p>You shut the car off and look underneath.</p><p>A plastic splash shield is hanging down and touching the pavement.</p><p>No fluid is leaking. Nothing is smoking.</p><div class="explain">Stopping safely gave you something valuable: information. The immediate emergency is smaller than it sounded, but dragging bodywork can still worsen damage or come loose while driving.</div><p class="impact">What do you do?</p>`, choices:[{ label:'Try to tear the loose panel off', detail:'Get rid of the problem and keep going.', next:'tearPanel' },{ label:'Inspect without crawling under the car', detail:'Decide whether help is needed without putting yourself underneath it.', next:'inspectPanel' }] },
    afterSwerveContinue: { text:`<p>You keep driving.</p><p>A block later, you notice something: your hands are still tight on the steering wheel and you’re following the next car much more closely than before.</p><div class="explain">Near-misses can narrow attention. After a sudden event, restoring following distance and scanning around the vehicle helps reset the situation instead of carrying the stress into the next decision.</div><p class="impact">What do you change?</p>`, choices:[{ label:'Back off and rebuild space', detail:'Give yourself more time for the next surprise.', next:'regainSpace' },{ label:'Stay close so nobody cuts in', detail:'You want to get to the store and be done with this.', next:'tailgateConsequence' }] },
    regainSpace: { text:`<p>You ease off the accelerator and rebuild a comfortable gap.</p><p>The road suddenly feels slower.</p><p>Not because traffic changed—because you gave yourself more time to see and decide.</p><div class="explain">Space is decision time. More following distance often turns a split-second emergency into an ordinary driving choice.</div><p>A few minutes later, you reach the grocery store.</p><p>As you park, you think about the rock again.</p><p class="impact">What do you take away from it?</p>`, choices:[{ label:'The safest move depends on the whole scene', detail:'Object size, traffic, speed, space, and vehicle clearance all matter.', next:'finish' },{ label:'Always swerve around road debris', detail:'Missing the object is the goal.', next:'nuanceFinish' }] },
    tailgateConsequence: { text:`<p>You stay close.</p><p>The car ahead brakes for a yellow light.</p><p>You brake harder than you wanted to.</p><p>Nothing bad happens—but now you’ve had two rushed decisions in five minutes.</p><div class="explain">The lesson isn’t “never make a mistake.” It’s that one tense moment can create the conditions for the next one. Rebuilding space breaks that chain.</div><p class="impact">Try something different?</p>`, choices:[{ label:'Yes — create more following distance', detail:'Give the next decision more time.', next:'regainSpace' }] },
    badContinue: { text:`<p>You keep driving.</p><p>The scraping suddenly stops.</p><p>For half a second, that feels like good news.</p><p>Then you see the loose panel tumbling behind you in the mirror.</p><p class="aside">Well. The car has solved the noise problem by donating a part to the roadway.</p><div class="explain">A problem disappearing is not always the same as a problem being solved. Continuing after new warning signs can turn a manageable issue into damage, debris, or a hazard for someone else.</div><p class="impact">What now?</p>`, choices:[{ label:'Pull over safely', detail:'Stop and reassess instead of gambling again.', next:'safeStopAfterLoss' }] },
    safeStopAfterLoss: { text:`<p>You pull into a safe lot and stop.</p><p>The panel is gone, but the car appears otherwise normal.</p><p>You’re no longer deciding whether to ignore the problem. You’re deciding how to deal with the damage you already know about.</p><div class="explain">Consequences change the decision tree. Once the panel came off, the earlier option—stop before it detached—disappeared. Real life works that way too: choices change what choices remain.</div><p class="impact">What would you do?</p>`, choices:[{ label:'Call for advice or inspection', detail:'Find out whether the car is safe to continue driving.', next:'finishImpact' },{ label:'Assume it was only plastic and continue', detail:'The car still seems fine.', next:'finishImpactRisk' }] },
    tearPanel: { text:`<p>You reach down and tug at the hanging panel.</p><p>It doesn’t want to come off.</p><p>To get a better grip, you would have to reach farther underneath the car.</p><div class="explain">This is where a minor car problem can become a personal-safety problem. A roadside fix is not worth putting yourself under a vehicle or into traffic without the right conditions and equipment.</div><p class="impact">Change your plan?</p>`, choices:[{ label:'Yes — stop pulling and get help', detail:'Keep the mechanical problem from becoming a people problem.', next:'inspectPanel' }] },
    inspectPanel: { text:`<p>You stay clear of traffic and avoid crawling under the car.</p><p>You take a photo from the side and call someone you trust for advice.</p><p>The recommendation: don’t keep driving with the panel dragging. Get it secured or removed properly.</p><div class="explain">You didn’t need to become a mechanic. You needed to recognize the limit of what was safe to handle yourself and know when to get help.</div><p class="impact">Adventure almost over. One last decision.</p>`, choices:[{ label:'Arrange help and protect the car from more damage', detail:'A small inconvenience now may prevent a larger one later.', next:'finishImpact' },{ label:'Drive slowly and hope the panel hangs on', detail:'The store is close.', next:'finishImpactRisk' }] },
    finishImpact: { ending:true, text:`<p>You arrange help.</p><p>The panel is secured, and the car is checked before you continue.</p><p>The groceries are late. The car survives.</p><p class="aside">The ice cream files a complaint.</p><div class="explain">You never needed a perfect first decision. The useful skill was continuing to update your choices as the situation changed.</div><p class="impact">That’s the point of DCG.</p><p>You make decisions. You see what they lead to. Then you decide what to do next.</p>`, choices:[{ label:'Run The Rock again', detail:'Choose a different path and see what changes.', next:'start', restart:true }] },
    finishImpactRisk: { ending:true, text:`<p>You decide to keep moving.</p><p>You make it to the store, but the dragging returns before you arrive.</p><p>Maybe nothing worse happens. Maybe the panel tears loose. Maybe it damages something else.</p><div class="explain">Some real-world choices don’t have a guaranteed immediate disaster attached to them. That uncertainty is exactly why risk matters. “It worked once” is not the same as “it was a good bet.”</div><p class="impact">End of this path.</p>`, choices:[{ label:'Run The Rock again', detail:'Try another set of decisions.', next:'start', restart:true }] },
    finish: { ending:true, text:`<p>Exactly.</p><p>The rock was never a trivia question with one magic answer.</p><p>The safer choice depends on the whole situation: your speed, traffic around you, available space, the size of the object, and what your vehicle can safely clear.</p><div class="explain">The bigger lesson is to create time and space whenever you can. The more of both you have, the fewer decisions have to be made in a panic.</div><p class="impact">Adventure complete.</p>`, choices:[{ label:'Run The Rock again', detail:'Take another path.', next:'start', restart:true }] },
    nuanceFinish: { ending:true, text:`<p>Sometimes swerving is exactly the right move.</p><p>Sometimes it creates the bigger hazard.</p><p>That’s why “always swerve” is too simple.</p><div class="explain">DCG is meant to teach judgment, not slogans. A good driver weighs the object ahead against the risks beside, behind, and underneath the vehicle.</div><p class="impact">Adventure complete.</p>`, choices:[{ label:'Run The Rock again', detail:'Try a different first decision.', next:'start', restart:true }] }
  }
};